//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoM
    {
        public int BillOfMaterialID { get; set; }
        public Nullable<int> ProductAssemblyID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public Nullable<int> UnitMeasureCode { get; set; }
        public Nullable<int> BoMLevel { get; set; }
        public Nullable<int> PerAssemblyQuantity { get; set; }
    }
}
