//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditReference
    {
        public int CreditReferenceID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
