//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceLineItem
    {
        public int invoiceID { get; set; }
        public int invoiceSequence { get; set; }
        public Nullable<decimal> invoiceLineItemPrice { get; set; }
        public Nullable<int> inventoryID { get; set; }
        public Nullable<int> quantityOfItem { get; set; }
        public string orderStatus { get; set; }
    
        public virtual inventory inventory { get; set; }
        public virtual invoice invoice { get; set; }
    }
}
