//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invoiceLineItems = new HashSet<invoiceLineItem>();
        }
    
        public int invoiceID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> shipmentType { get; set; }
        public Nullable<decimal> orderTotalPrice { get; set; }
        public Nullable<System.DateTime> estimatedShippingDate { get; set; }
        public Nullable<System.DateTime> invoiceDateTime { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoiceLineItem> invoiceLineItems { get; set; }
    }
}
