//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderLine
    {
        public int POid { get; set; }
        public int PurchaseOrderLineID { get; set; }
        public Nullable<decimal> PurchaseOrderLineItemPrice { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
